name: Deploy to Github Pages

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # .NET Core環境の構築
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.4.0
      with:
      # Blazor WebAssemblyが使えるSDKを指定
        dotnet-version: '3.1.300'
    - name: Build Application
      # デプロイするProjectを指定 (今回は"HelloBlazorWasm")
      run: dotnet publish -o ./docs -c Release ./HelloBlazorWasm/HelloBlazorWasm.csproj
